- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh"
  become: true

  pre_tasks:
  - name: update repositories
    apt: update_cache=yes
    changed_when: False

  tasks:
  - include: tasks/config-ssh.yml
  - include: tasks/dotfiles.yml
  - include: tasks/node-setup.yml
  - include: tasks/python-setup.yml
  