- name: "Fetch uv"
  ansible.builtin.get_url:
    url: "https://astral.sh/uv/install.sh"
    dest: "/tmp/install.sh"
    mode: "0755"

- name: "Install uv via bash"
  ansible.builtin.shell: "/tmp/install.sh"

- name: "Update uv"
  ansible.builtin.shell:
    cmd: "uv self update"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  tags:
    - install
    - python
