- name: "Install uv via bash"
  ansible.builtin.shell:
    cmd: "curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR='/usr/local/bin' sh"

- name: "Update uv"
  ansible.builtin.shell:
    cmd: "uv self update"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  tags:
    - install
    - python
